from __future__ import annotations

import os
import platform
import subprocess
import tempfile
import threading
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, Optional

import portalocker
import yaml
from pydantic import AliasChoices, BaseModel, ConfigDict, Field

from . import cli_entry
from .config import (
    ConfigError,
    DEFAULT_STATE_FILE_PATH,
    DEFAULT_VERSION_CHECK_ENABLED,
    DEFAULT_VERSION_CHECK_INTERVAL_SEC,
    load_agents_config,
    load_config,
    load_global_config_from_path,
)
from .agents_modules import get_agent_class
from .agent_version_sources import AgentVersionCheckError
from .versioning import is_newer_version, latest_version_via_pip, normalize_version, runtime_version

STATE_FILE_HEADER = "# Do not edit this file manually; it is generated by agsekit.\n"
CHANGELOG_URL = "https://github.com/MihanEntalpo/agent-safety-kit/blob/main/changelog.md"
VERSION_CHECK_DAEMON_ENV_VAR = "AGSEKIT_ENABLE_DAEMON_VERSION_CHECK"
AGENT_VERSION_CHECK_MAX_AGE = timedelta(days=1)


class AgentVersionStateModel(BaseModel):
    """Latest installable version observed for one configured agent type."""

    model_config = ConfigDict(extra="ignore")

    latest_version: str
    updated_at: str


class AgsekitStateModel(BaseModel):
    """Validated agsekit runtime state persisted to state.yaml."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    current_version: str
    last_version: str = Field(
        alias="last_Version",
        validation_alias=AliasChoices("last_Version", "last_version"),
        serialization_alias="last_Version",
    )
    agent_versions: Dict[str, AgentVersionStateModel] = Field(default_factory=dict)


class StateManager:
    """Keep an in-memory state snapshot in sync with the YAML state file."""

    def __init__(self, path: Path) -> None:
        self.path = path.expanduser()
        self.lock_path = self.path.with_name(f"{self.path.name}.lock")
        self._lock = threading.RLock()
        self._state = self._load_state()

    @property
    def current_version(self) -> str:
        with self._lock:
            return self._state.current_version

    @property
    def last_version(self) -> str:
        with self._lock:
            return self._state.last_version

    def get_agent_version(self, agent_type: str) -> Optional[AgentVersionStateModel]:
        with self._lock:
            entry = self._state.agent_versions.get(agent_type)
            return entry.model_copy() if entry is not None else None

    def agent_version_is_due(
        self,
        agent_type: str,
        *,
        now: Optional[datetime] = None,
        max_age: timedelta = AGENT_VERSION_CHECK_MAX_AGE,
    ) -> bool:
        entry = self.get_agent_version(agent_type)
        if entry is None:
            return True
        updated_at = _parse_utc_timestamp(entry.updated_at)
        if updated_at is None:
            return True
        current_time = now or datetime.now(timezone.utc)
        return current_time - updated_at >= max_age

    def has_newer_version(self) -> bool:
        with self._lock:
            return is_newer_version(self._state.last_version, self._state.current_version)

    def update_current_version(self, version: str) -> None:
        normalized = normalize_version(version) or self.current_version

        def _update(state: AgsekitStateModel) -> None:
            state.current_version = normalized
            if not normalize_version(state.last_version):
                state.last_version = normalized

        self._update_locked(_update)

    def update_last_version(self, version: str) -> None:
        normalized = normalize_version(version) or self.current_version
        self._update_locked(lambda state: setattr(state, "last_version", normalized))

    def update_agent_version(self, agent_type: str, version: str, *, updated_at: datetime) -> None:
        normalized = normalize_version(version)
        if normalized is None:
            raise ValueError(f"Invalid agent version for {agent_type}: {version}")
        timestamp = _format_utc_timestamp(updated_at)

        def _update(state: AgsekitStateModel) -> None:
            state.agent_versions[agent_type] = AgentVersionStateModel(
                latest_version=normalized,
                updated_at=timestamp,
            )

        self._update_locked(_update)

    def _load_state(self) -> AgsekitStateModel:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with portalocker.Lock(str(self.lock_path), mode="a", timeout=60):
            return self._load_state_file_locked(canonicalize=True)

    def _load_state_file_locked(self, *, canonicalize: bool) -> AgsekitStateModel:
        current = normalize_version(runtime_version()) or "0"
        raw_payload: Any = {}
        if self.path.exists():
            try:
                raw_payload = yaml.safe_load(self.path.read_text(encoding="utf-8")) or {}
            except Exception:
                raw_payload = {}

        sanitized = _sanitize_state_payload(raw_payload, current)
        state = AgsekitStateModel.model_validate(sanitized)
        rendered = _render_state(state)
        if canonicalize and (
            not self.path.exists() or self.path.read_text(encoding="utf-8", errors="replace") != rendered
        ):
            self._write_state_file_locked(rendered)
        return state

    def _update_locked(self, callback: Any) -> None:
        with self._lock:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with portalocker.Lock(str(self.lock_path), mode="a", timeout=60):
                state = self._load_state_file_locked(canonicalize=False)
                before = _render_state(state)
                callback(state)
                after = _render_state(state)
                if after != before or not self.path.exists():
                    self._write_state_file_locked(after)
                self._state = state

    def _write_state_file_locked(self, content: str) -> None:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{self.path.name}.",
            suffix=".tmp",
            dir=str(self.path.parent),
        )
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary_name, self.path)
        finally:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass


def _sanitize_state_payload(raw_payload: Any, current_version: str) -> Dict[str, Any]:
    payload = raw_payload if isinstance(raw_payload, dict) else {}
    last_version = normalize_version(payload.get("last_Version"))
    if last_version is None:
        last_version = normalize_version(payload.get("last_version"))
    if last_version is None:
        last_version = current_version
    agent_versions: Dict[str, Dict[str, str]] = {}
    raw_agent_versions = payload.get("agent_versions")
    if isinstance(raw_agent_versions, dict):
        for agent_type, raw_entry in raw_agent_versions.items():
            if not isinstance(agent_type, str) or not isinstance(raw_entry, dict):
                continue
            latest_version = normalize_version(raw_entry.get("latest_version"))
            updated_at = _normalize_utc_timestamp(raw_entry.get("updated_at"))
            if latest_version is None or updated_at is None:
                continue
            agent_versions[agent_type] = {
                "latest_version": latest_version,
                "updated_at": updated_at,
            }
    return {
        "current_version": current_version,
        "last_Version": last_version,
        "agent_versions": agent_versions,
    }


def _parse_utc_timestamp(value: object) -> Optional[datetime]:
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        parsed = datetime.fromisoformat(value.strip().replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _format_utc_timestamp(value: datetime) -> str:
    normalized = value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)
    return normalized.astimezone(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _normalize_utc_timestamp(value: object) -> Optional[str]:
    parsed = _parse_utc_timestamp(value)
    return _format_utc_timestamp(parsed) if parsed is not None else None


def _render_state(state: AgsekitStateModel) -> str:
    return STATE_FILE_HEADER + yaml.safe_dump(
        state.model_dump(by_alias=True),
        sort_keys=False,
        allow_unicode=True,
    )


_STATE_MANAGER: Optional[StateManager] = None


def _resolve_state_path(config_path: Optional[Path]) -> Path:
    try:
        return load_global_config_from_path(config_path, allow_missing=True).state_file
    except ConfigError:
        return DEFAULT_STATE_FILE_PATH


def initialize_state(config_path: Optional[Path] = None) -> StateManager:
    """Initialize the process-global state manager using the config-specific state file when possible."""
    global _STATE_MANAGER
    manager = StateManager(_resolve_state_path(config_path))
    _STATE_MANAGER = manager
    return manager


def get_state_manager() -> StateManager:
    """Return the process-global state manager, initializing it with defaults if needed."""
    global _STATE_MANAGER
    if _STATE_MANAGER is None:
        _STATE_MANAGER = initialize_state(None)
    return _STATE_MANAGER


def refresh_configured_agent_versions(
    config_path: Optional[Path],
    *,
    now: Optional[datetime] = None,
) -> Dict[str, str]:
    """Refresh due latest-version entries for unique agent types from the config."""
    if config_path is None or not config_path.exists():
        return {}
    config = load_config(config_path)
    agent_types = {agent.type for agent in load_agents_config(config).values()}
    return refresh_agent_versions(agent_types, now=now)


def refresh_agent_versions(
    agent_types: Iterable[str],
    *,
    now: Optional[datetime] = None,
    force: bool = False,
) -> Dict[str, str]:
    """Refresh latest-version entries for the requested unique agent types."""
    manager = get_state_manager()
    current_time = now or datetime.now(timezone.utc)
    architecture = platform.machine()
    errors: Dict[str, str] = {}
    for agent_type in sorted(set(agent_types)):
        if not force and not manager.agent_version_is_due(agent_type, now=current_time):
            continue
        try:
            latest = get_agent_class(agent_type).check_latest_version(
                architecture=architecture,
            )
            manager.update_agent_version(agent_type, latest, updated_at=current_time)
        except (AgentVersionCheckError, RuntimeError, ValueError) as exc:
            errors[agent_type] = str(exc)
    return errors


def run_check_new_version(config_path: Optional[Path] = None) -> str:
    """Query latest agsekit and configured-agent versions and persist them into state."""
    refresh_configured_agent_versions(config_path)
    latest = latest_version_via_pip("agsekit")
    manager = get_state_manager()
    manager.update_last_version(latest)
    return latest


def _background_check_command(config_path: Optional[Path]) -> list[str]:
    command = cli_entry.resolve_agsekit_command("daemon.cli_not_found")
    command.extend(["check-new-version", "--non-interactive"])
    if config_path is not None:
        command.extend(["--config", str(config_path)])
    return command


def start_periodic_version_check_thread(config_path: Optional[Path], *, debug: bool = False) -> threading.Event:
    """Start a daemon thread that periodically launches `agsekit check-new-version`."""
    stop_event = threading.Event()
    resolved_config_path = config_path.resolve() if config_path is not None else None

    def _loop() -> None:
        while not stop_event.is_set():
            enabled = DEFAULT_VERSION_CHECK_ENABLED
            interval = DEFAULT_VERSION_CHECK_INTERVAL_SEC
            try:
                global_config = load_global_config_from_path(resolved_config_path, allow_missing=True)
                enabled = global_config.check_new_version
                interval = global_config.check_new_version_interval_sec
            except ConfigError:
                pass

            if enabled:
                try:
                    subprocess.run(
                        _background_check_command(resolved_config_path),
                        check=False,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                except Exception:
                    if debug:
                        pass

            if stop_event.wait(interval):
                return

    thread = threading.Thread(target=_loop, daemon=True, name="agsekit-version-check")
    thread.start()
    return stop_event
