from __future__ import annotations

import subprocess
import threading
from pathlib import Path
from typing import Any, Dict, Optional

import yaml
from pydantic import AliasChoices, BaseModel, ConfigDict, Field

from . import cli_entry
from .config import (
    ConfigError,
    DEFAULT_STATE_FILE_PATH,
    DEFAULT_VERSION_CHECK_ENABLED,
    DEFAULT_VERSION_CHECK_INTERVAL_SEC,
    load_global_config_from_path,
)
from .versioning import is_newer_version, latest_version_via_pip, normalize_version, runtime_version

STATE_FILE_HEADER = "# Do not edit this file manually; it is generated by agsekit.\n"
CHANGELOG_URL = "https://github.com/MihanEntalpo/agent-safety-kit/blob/main/changelog.md"
VERSION_CHECK_DAEMON_ENV_VAR = "AGSEKIT_ENABLE_DAEMON_VERSION_CHECK"


class AgsekitStateModel(BaseModel):
    """Validated agsekit runtime state persisted to state.yaml."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    current_version: str
    last_version: str = Field(
        alias="last_Version",
        validation_alias=AliasChoices("last_Version", "last_version"),
        serialization_alias="last_Version",
    )


class StateManager:
    """Keep an in-memory state snapshot in sync with the YAML state file."""

    def __init__(self, path: Path) -> None:
        self.path = path.expanduser()
        self._lock = threading.RLock()
        self._state = self._load_state()

    @property
    def current_version(self) -> str:
        with self._lock:
            return self._state.current_version

    @property
    def last_version(self) -> str:
        with self._lock:
            return self._state.last_version

    def has_newer_version(self) -> bool:
        with self._lock:
            return is_newer_version(self._state.last_version, self._state.current_version)

    def update_current_version(self, version: str) -> None:
        normalized = normalize_version(version) or self._state.current_version
        with self._lock:
            if self._state.current_version == normalized:
                return
            self._state.current_version = normalized
            if not normalize_version(self._state.last_version):
                self._state.last_version = normalized
            self._save_locked()

    def update_last_version(self, version: str) -> None:
        normalized = normalize_version(version) or self._state.current_version
        with self._lock:
            if self._state.last_version == normalized:
                return
            self._state.last_version = normalized
            self._save_locked()

    def _load_state(self) -> AgsekitStateModel:
        current = normalize_version(runtime_version()) or "0"
        raw_payload: Any = {}
        if self.path.exists():
            try:
                raw_payload = yaml.safe_load(self.path.read_text(encoding="utf-8")) or {}
            except Exception:
                raw_payload = {}

        sanitized = _sanitize_state_payload(raw_payload, current)
        state = AgsekitStateModel.model_validate(sanitized)
        rendered = _render_state(state)
        if not self.path.exists() or self.path.read_text(encoding="utf-8", errors="replace") != rendered:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            self.path.write_text(rendered, encoding="utf-8")
        return state

    def _save_locked(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(_render_state(self._state), encoding="utf-8")


def _sanitize_state_payload(raw_payload: Any, current_version: str) -> Dict[str, str]:
    payload = raw_payload if isinstance(raw_payload, dict) else {}
    last_version = normalize_version(payload.get("last_Version"))
    if last_version is None:
        last_version = normalize_version(payload.get("last_version"))
    if last_version is None:
        last_version = current_version
    return {
        "current_version": current_version,
        "last_Version": last_version,
    }


def _render_state(state: AgsekitStateModel) -> str:
    return STATE_FILE_HEADER + yaml.safe_dump(
        state.model_dump(by_alias=True),
        sort_keys=False,
        allow_unicode=True,
    )


_STATE_MANAGER: Optional[StateManager] = None


def _resolve_state_path(config_path: Optional[Path]) -> Path:
    try:
        return load_global_config_from_path(config_path, allow_missing=True).state_file
    except ConfigError:
        return DEFAULT_STATE_FILE_PATH


def initialize_state(config_path: Optional[Path] = None) -> StateManager:
    """Initialize the process-global state manager using the config-specific state file when possible."""
    global _STATE_MANAGER
    manager = StateManager(_resolve_state_path(config_path))
    _STATE_MANAGER = manager
    return manager


def get_state_manager() -> StateManager:
    """Return the process-global state manager, initializing it with defaults if needed."""
    global _STATE_MANAGER
    if _STATE_MANAGER is None:
        _STATE_MANAGER = initialize_state(None)
    return _STATE_MANAGER


def run_check_new_version() -> str:
    """Query pip for the newest published agsekit version and persist it into state."""
    latest = latest_version_via_pip("agsekit")
    manager = get_state_manager()
    manager.update_last_version(latest)
    return latest


def _background_check_command(config_path: Optional[Path]) -> list[str]:
    command = cli_entry.resolve_agsekit_command("daemon.cli_not_found")
    command.extend(["check-new-version", "--non-interactive"])
    if config_path is not None:
        command.extend(["--config", str(config_path)])
    return command


def start_periodic_version_check_thread(config_path: Optional[Path], *, debug: bool = False) -> threading.Event:
    """Start a daemon thread that periodically launches `agsekit check-new-version`."""
    stop_event = threading.Event()
    resolved_config_path = config_path.resolve() if config_path is not None else None

    def _loop() -> None:
        while not stop_event.is_set():
            enabled = DEFAULT_VERSION_CHECK_ENABLED
            interval = DEFAULT_VERSION_CHECK_INTERVAL_SEC
            try:
                global_config = load_global_config_from_path(resolved_config_path, allow_missing=True)
                enabled = global_config.check_new_version
                interval = global_config.check_new_version_interval_sec
            except ConfigError:
                pass

            if enabled:
                try:
                    subprocess.run(
                        _background_check_command(resolved_config_path),
                        check=False,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                except Exception:
                    if debug:
                        pass

            if stop_event.wait(interval):
                return

    thread = threading.Thread(target=_loop, daemon=True, name="agsekit-version-check")
    thread.start()
    return stop_event
