from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

from agsekit_cli.agents_modules import SUPPORTED_AGENT_TYPES
from tests.integration.utils import (
    REPO_ROOT,
    clean_env,
    random_vm_name,
    require_host_tools,
    run_cli,
    run_process,
    write_config,
)


pytestmark = pytest.mark.host_integration
pexpect = pytest.importorskip("pexpect")


@pytest.mark.skipif(os.name == "nt", reason="pexpect-based config-gen smoke test requires a POSIX PTY")
def test_config_example_and_gen(tmp_path: Path) -> None:
    example_path = tmp_path / "config-example.yaml"
    run_cli(["config-example", str(example_path)], check=True, cwd=tmp_path)
    assert example_path.exists()

    generated_path = tmp_path / "config-gen.yaml"
    env = clean_env(
        {
            "AGSEKIT_LANG": "en",
            "TERM": "xterm-256color",
            "PYTHONUNBUFFERED": "1",
            "COLUMNS": "120",
            "LINES": "40",
        }
    )
    child = pexpect.spawn(
        sys.executable,
        [str(REPO_ROOT / "agsekit"), "config-gen", "--config", str(generated_path), "--overwrite"],
        cwd=str(tmp_path),
        env=env,
        encoding="utf-8",
        timeout=20,
    )

    child.expect_exact("VM name")
    child.sendline("")
    child.expect_exact("How many vCPUs to allocate")
    child.sendline("")
    child.expect_exact("RAM size")
    child.sendline("")
    child.expect_exact("Disk size")
    child.sendline("")
    child.expect_exact("Select install bundles for this VM")
    child.sendline("")
    child.expect_exact("Proxychains proxy URL")
    child.sendline("")
    child.expect_exact("VM HTTP proxy URL")
    child.sendline("")
    child.expect_exact("Configure port-forwarding for this VM?")
    child.send("n")
    child.expect_exact("Add another VM?")
    child.send("n")
    child.expect_exact("Agent type")
    child.expect_exact("Cancel")
    child.send("j" * len(SUPPORTED_AGENT_TYPES))
    child.send("\r")
    child.expect_exact("Do you want to configure mounts?")
    child.send("n")
    child.expect_exact("Customize global agsekit settings?")
    child.send("n")
    child.expect_exact("Where should the config be saved?")
    child.sendline("")
    child.expect(pexpect.EOF)
    child.close()

    assert child.exitstatus == 0, child.before
    assert generated_path.exists()

    config = yaml.safe_load(generated_path.read_text(encoding="utf-8"))
    assert config == {
        "vms": {
            "agent-ubuntu": {
                "cpu": 2,
                "ram": "4G",
                "disk": "20G",
            }
        }
    }


def test_list_bundles_and_version() -> None:
    bundles = run_cli(["list-bundles"], check=True)
    assert "docker" in bundles.stdout

    version = run_cli(["version"], check=True)
    assert version.stdout.strip()


def test_pip_upgrade_runs() -> None:
    result = run_cli(["pip-upgrade"], check=True)
    assert result.returncode == 0


def test_check_new_version_updates_custom_state_file(tmp_path: Path) -> None:
    state_path = tmp_path / "state.yaml"
    config_path = tmp_path / "config.yaml"
    write_config(
        config_path,
        {
            "global": {
                "state_file": str(state_path),
                "check_new_version": False,
            }
        },
    )

    result = run_cli(["check-new-version", "--config", str(config_path)], check=True, cwd=tmp_path)
    assert result.returncode == 0
    assert state_path.exists()

    raw_state = state_path.read_text(encoding="utf-8")
    assert raw_state.startswith("# Do not edit this file manually; it is generated by agsekit.\n")

    payload = yaml.safe_load(raw_state)
    assert payload["current_version"]
    assert payload["last_Version"]
    assert "check-new-version" not in result.stderr


def test_shell_requires_vm_when_multiple(tmp_path: Path) -> None:
    vm_one = random_vm_name("it-shell")
    vm_two = random_vm_name("it-shell")
    config_path = tmp_path / "config.yaml"
    write_config(
        config_path,
        {
            "vms": {
                vm_one: {"cpu": 1, "ram": "1G", "disk": "5G"},
                vm_two: {"cpu": 1, "ram": "1G", "disk": "5G"},
            }
        },
    )
    result = run_cli(["shell", "--config", str(config_path), "--non-interactive"], check=False)
    assert result.returncode != 0


def test_doctor_smoke(tmp_path: Path) -> None:
    require_host_tools()
    run_cli(["prepare", "--non-interactive"], check=True)
    vm_name = random_vm_name("it-doctor")
    config_path = tmp_path / "config.yaml"
    write_config(
        config_path,
        {
            "vms": {
                vm_name: {"cpu": 1, "ram": "1G", "disk": "5G"},
            }
        },
    )
    run_cli(["doctor", "--config", str(config_path), "--non-interactive"], check=True)
